---
title: "Final project"
author: "Xing Cheng, Jihyun Lee, Hyunjoe Yoo"
date: "11/10/2021"
output: pdf_document
---

[Xing]
```{r}
#install.packages("tidycensus")
library(tidycensus)
library(httr)
library(jsonlite)
#install.packages("sqldf")
library(sqldf)
library(tidyverse)
```

```{r}
# I will figure out API later
res2019 = GET("https://data.medicaid.gov/api/1/metastore/schemas/dataset/items/e36d89c0-f62e-56d5-bc7e-b0adf89262b8?show-reference-ids=false")
res2019=fromJSON(rawToChar(res2019$content))
downloadURL2019=res2019$distribution$data$downloadURL
data2019=read.csv(downloadURL2019)

res2020=GET("https://data.medicaid.gov/api/1/metastore/schemas/dataset/items/fbbe1734-b448-4e5a-bc94-3f8688534741?show-reference-ids=false")
res2020=fromJSON(rawToChar(res2020$content))
downloadURL2020=res2020$distribution$data$downloadURL
data2020=read.csv(downloadURL2020)
```




```{r}
data=sqldf("select * from data2019
      union all
      select * from data2020")
```


```{r}
#Remove dot from column names
names(data) <- gsub("\\.", "", names(data))
names(data)
```
Investigated data using excel, I found the column Source is constant value 
```{r}
SourceAbb=sqldf("
select *, row_number() over (order by FFY,Source) as source_id
from
(select distinct FFY, Source from data) temp")

```

```{r}
MeasureInfo=sqldf("
select distinct MeasureAbbreviation, ReportingProgram, Domain, MeasureName, MeasureType, RateDefinition
from data
              ")
```

```{r}
StateReport=sqldf("select State, MeasureAbbreviation, data.FFY, source_id, Population, Methodology, StateRate, NumberofStatesReporting, Median, BottomQuartile, TopQuartile, Notes, StateSpecificComments, RateUsedinCalculatingStateMeanandMedian
      from data, SourceAbb
      where data.FFY=SourceAbb.FFY and data.Source=SourceAbb.Source")
```


```{r}
#install.packages("usmap")
library(usmap)
library(ggplot2)

State_report_freq_2020=sqldf("
select State as state, count(State) as report_freq
from data
where FFY=2020
group by State
order by report_freq desc
      ")

plot_usmap(data=State_report_freq,values='report_freq',color="red")+
  scale_fill_continuous(low="white",high="blue",name="report freq 2020",label=scales::comma)+
  theme(legend.position='right')
```

```{r}
State_report_freq_2019=sqldf("
select State as state, count(State) as report_freq
from data
where FFY=2019
group by State
order by report_freq desc
      ")

plot_usmap(data=State_report_freq,values='report_freq',color="red")+
  scale_fill_continuous(low="white",high="blue",name="report freq 2019",label=scales::comma)+
  theme(legend.position='right')


```


[Jihyun]
I have two parts, 1: higher is better, made two separate columns 2019 and 2020 to compare. 2: lower is better.
My code will generate new csv files, Hannah will generate the bar graphs to compare two average state rates.

Average state rate for "higher is better" in **2019 and 2020**
```{r fig.show = 'hold', out.width = '50%'}
names(data2019) <- gsub("\\.", "", names(data2019))
#names(data2019)

higher2019=sqldf("select State, avg(StateRate) as StateRate_mean
from data2019
where MeasureType like 'Higher%'
group by State
order by StateRate_mean desc
      ")

par(mar = c(7, 4, 2, 2) + 0.2)
end_point = 0.5 + nrow(higher2019) + nrow(higher2019) - 1
barplot(higher2019$StateRate_mean, col = "grey50",
        main = "",
        ylab = "2019 State Mean (higher is better)", ylim = c(0,70),
        xlab = "",
        space = 1)
text(seq(1.5, end_point, by = 2), par("usr")[3]-0.25,
     srt = 60, adj = 1, xpd = TRUE,
     labels = paste(higher2019$State), cex = 0.65)

names(data2020) <- gsub("\\.", "", names(data2020))

higher2020=sqldf("select State, avg(StateRate) as StateRate_mean
from data2020
where MeasureType like 'Higher%'
group by State
order by StateRate_mean desc
      ")

par(mar = c(7, 4, 2, 2) + 0.2)
end_point = 0.5 + nrow(higher2020) + nrow(higher2020) - 1
barplot(higher2019$StateRate_mean, col = "lightblue",
        main = "",
        ylab = "2020 State Mean (higher is better)", ylim = c(0,70),
        xlab = "",
        space = 1)
text(seq(1.5, end_point, by = 2), par("usr")[3]-0.25,
     srt = 60, adj = 1, xpd = TRUE,
     labels = paste(higher2020$State), cex = 0.65)

h2019 <- higher2019[order(higher2019$State),]
h2020 <- higher2020[order(higher2020$State),]
h2020<- h2020[-40,] #I dropped Pueto Rico because 2019 data doesn't have Pueto Rico.

higher2019_2020<- h2019
higher2019_2020$StateRate_mean_2020<-h2020$StateRate_mean
colnames(higher2019_2020)[2] <- "StateRate_mean_2019"

write.csv(higher2019_2020,"higherbetter_StateRateMean_2019_2020_combine.csv", row.names = FALSE)


```

Average state rate for "lower is better" in 2019 and 2020

```{r fig.show = 'hold', out.width = '32%'}
#names(data2019) <- gsub("\\.", "", names(data2019))
#names(data2019)

lower2019=sqldf("select State, avg(StateRate) as StateRate_mean
from data2019
where MeasureType like 'Lower%'
group by State
order by StateRate_mean desc
      ")

par(mar = c(7, 4, 2, 2) + 0.2)
end_point = 0.5 + nrow(lower2019) + nrow(lower2019) - 1
barplot(lower2019$StateRate_mean, col = "grey50",
        main = "",
        ylab = "2019 State Mean (lower is better)", ylim = c(0,70),
        xlab = "",
        space = 1)
text(seq(1.5, end_point, by = 2), par("usr")[3]-0.25,
     srt = 60, adj = 1, xpd = TRUE,
     labels = paste(lower2019$State), cex = 0.65)

#names(data2020) <- gsub("\\.", "", names(data2020))

lower2020=sqldf("select State, avg(StateRate) as StateRate_mean
from data2020
where MeasureType like 'Lower%'
group by State
order by StateRate_mean desc
      ")

par(mar = c(7, 4, 2, 2) + 0.2)
end_point = 0.5 + nrow(lower2020) + nrow(lower2020) - 1
barplot(lower2019$StateRate_mean, col = "lightblue",
        main = "",
        ylab = "2020 State Mean (lower is better)", ylim = c(0,70),
        xlab = "",
        space = 1)
text(seq(1.5, end_point, by = 2), par("usr")[3]-0.25,
     srt = 60, adj = 1, xpd = TRUE,
     labels = paste(lower2020$State), cex = 0.65)

l2019 <- lower2019[order(lower2019$State),]
l2020 <- lower2020[order(lower2020$State),]
l2020<- l2020[-40,] #I dropped Pueto Rico because 2019 data doesn't have Pueto Rico.

lower2019_2020<- l2019
lower2019_2020$StateRate_mean_2020<-l2020$StateRate_mean
colnames(lower2019_2020)[2] <- "StateRate_mean_2019"

write.csv(lower2019_2020,"lowerbetter_StateRateMean_2019_2020_combine.csv", row.names = FALSE)


```
